version: 0.2
phases:
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t 929806479990.dkr.ecr.us-east-1.amazonaws.com/expose8080:latest .
  post_build:
    commands:
      - echo "Pushing Docker image..."
      - docker push 929806479990.dkr.ecr.us-east-1.amazonaws.com/expose8080:latest
      # - echo "Deploying to EKS..."
      # - kubectl apply -f deployment.yaml
