version: 0.2

env:
  secrets-manager:
    DOCKER_HUB_USERNAME: "dockerhub-cred-UCtbuX:DOCKER_HUB_USERNAME"  # Reference to your secret's key for username
    DOCKER_HUB_PASSWORD: "dockerhub-cred-UCtbuX:DOCKER_HUB_PASSWORD"  # Reference to your secret's key for password
    ECR_REPO_URI: "929806479990.dkr.ecr.us-east-1.amazonaws.com/myrepo"  # Your ECR repository URI

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - apt-get update && apt-get install -y docker.io awscli
      - service docker start
      - aws --version  # Verify AWS CLI is installed
      - docker --version  # Verify Docker is installed
  pre_build:
    commands:
      - echo "Logging in to Docker Hub..."
      - echo $DOCKER_HUB_PASSWORD | docker login --username $DOCKER_HUB_USERNAME --password-stdin
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 929806479990.dkr.ecr.us-east-1.amazonaws.com/myrepo
  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t 929806479990.dkr.ecr.us-east-1.amazonaws.com/myrepo:latest .
      - echo Tagging the Docker image...
      - docker tag 929806479990.dkr.ecr.us-east-1.amazonaws.com/nodejs:latest 929806479990.dkr.ecr.us-east-1.amazonaws.com/myrepo:latest
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 929806479990.dkr.ecr.us-east-1.amazonaws.com/myrepo:latest
      - echo Writing image definitions file...
      - echo '{"ImageURI":"929806479990.dkr.ecr.us-east-1.amazonaws.com/nodejs:latest"}' > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
