version: 0.2

phases:
  install:
    commands:
      - echo "Updating package list..."
      - apt-get update -y
      - echo "Installing Docker..."
      - apt-get install -y docker.io
      - echo "Starting Docker service..."
      - service docker start
      - echo "Installing AWS CLI..."
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - sudo ./aws/install
      - aws --version  # Verify AWS CLI installation
      - docker --version  # Verify Docker installation

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/y5w4k1m3

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t cicd .
      - docker tag my-app:latest public.ecr.aws/y5w4k1m3/cicd:latest
      - docker push public.ecr.aws/y5w4k1m3/cicd:latest























# version: 0.2

# phases:
#   install:
#     commands:
#       - echo "Installing dependencies..."
#       - apt-get update && apt-get install -y docker.io awscli

#   pre_build:
#     commands:
#       - echo "Logging in to Amazon ECR..."
#       - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/y5w4k1m3

#   build:
#     commands:
#       - echo "Building Docker image..."
#       - docker build -t cicd .

#   post_build:
#     commands:
#       - echo "Pushing Docker image to Amazon ECR..."
#       - docker push public.ecr.aws/y5w4k1m3/cicd:latest
