version: 0.2

phases:

  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo "Ayman@DOC12" | docker login --username "ayman380" --password-stdin
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t cidemo:latest .
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker tag cidemo:latest ayman380/cidemo:latest
      - docker push ayman380/cidemo:latest
