version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - apt-get update && apt-get install -y docker.io awscli

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr-public get-login-password --region us-east-1 | docker login --username Ayman --password-stdin public.ecr.aws/y5w4k1m3

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t cicd .

  post_build:
    commands:
      - echo "Pushing Docker image to Amazon ECR..."
      - docker push public.ecr.aws/y5w4k1m3/cicd:latest
