# name: Hello World
# on: [push]
# jobs:
#   Hello-World-Job:
#     runs-on:
#       - codebuild--${{ github.run_id }}-${{ github.run_attempt }}
#     steps:
#       - run: echo "Hello World"
# ========================================================================================================
# name: CI/CD Pipeline

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1

#       - name: Login to Docker Hub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKER_HUB_USERNAME }}
#           password: ${{ secrets.DOCKER_HUB_TOKEN }}

#       - name: Build and push Docker image
#         run: |
#           docker build -t ayman380/node-js:v3 .
#           docker push ayman380/node-js:v3

#   deploy:
#     needs: build
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: us-east-1

#       - name: Install kubectl
#         run: |
#           curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
#           sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          
#       - name: Update kubeconfig
#         run: |
#           aws eks --region us-east-1 update-kubeconfig --name Demo-Test 
          
      - name: Deploy to EKS
        run: |
          kubectl apply -f NodeJSDeployment.yaml
          kubectl apply -f NodeJSservice.yaml
